name: komari

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
      - "v*.*.*"
    tags:
      - "v*.*.*"
    paths-ignore:
      - "**/*.md"
      - "examples/**"
      - "docs/**"
  pull_request:
    branches:
      - "master"
      - "v*.*.*"
    paths-ignore:
      - "**/*.md"
      - "examples/**"
      - "docs/**"

permissions:
  contents: write

jobs:
  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      # TODO: https://github.com/DioxusLabs/dioxus/issues/3433
      # TODO: Need to add dx fmt
      - run: cargo fmt --check
      - run: cargo clippy -- -D warnings
      - run: cargo test -- --no-capture

  build:
    runs-on: windows-latest

    strategy:
      matrix:
        type: [release, debug]

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Build ${{ matrix.type }}
        shell: pwsh
        run: |
          $args = "--verbose", "--package", "ui"
          if ("${{ matrix.type }}" -eq "release") {
            $args += "--release"
          }
          dx build @args

      - uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.type }}
          path: target/dx/ui/${{ matrix.type }}/windows/app

      - if: startsWith(github.ref, 'refs/tags/')
        run: Compress-Archive -Path target/dx/ui/${{ matrix.type }}/windows/app/* -Destination app-${{ matrix.type }}.zip

      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            app-${{ matrix.type }}.zip
